export const VIEW_W = window.innerWidth;
export const VIEW_H = window.innerHeight;
export const MAP_W = VIEW_W * 3;
export const MAP_H = VIEW_H * 3;
export const CENTER = { x: MAP_W / 2, y: MAP_H / 2 };
export const PLAYER_SIZE = 36;
export const BIRD_SIZE = 24;
export const HUNTER_SIZE = 30;
export const PLAYER_SPEED = 12; // px/frame 기준(60fps 가정)
export const BIRD_SPEED_BASE_MULT = 1.08;
export const BIRD_STAGE_MULT = 1.1; // stage마다 곱
export const BIRD_MAXIMUM_COUNT = 100;
export const HUNTER_SPEED_MULT = 8;
export const HUNTER_MAXIMUM_COUNT = 12;
export const BIRD_SPAWN_PER_SEC = 3; // 초당
export const STAGE_SECONDS = 60;
export const BIRD_FOLLOW_TIME = 50;